jenkins:
  controller:
    jenkinsUriPrefix: /jenkins
    additionalPlugins: 
      - ant:latest
      - antisamy-markup-formatter:latest
      - authorize-project:latest
      - build-timeout:latest
      - cloudbees-folder:latest
      - credentials:latest
      - email-ext:latest
      - gradle:latest
      - job-dsl:latest
      - ldap:latest
      - mailer:latest
      - matrix-auth:latest
      - nodejs:latest
      - pam-auth:latest
      - pipeline-stage-view:latest
      - ssh-slaves:latest
      - timestamper:latest
      - ws-cleanup:latest
      - github:latest
    JCasC:
      configScripts:
        bootstrap-job: |
          jobs:
            - script: >
                pipelineJob("Seed or update all pipelines") {
                  triggers {
                    githubPush()
                  }
                  definition {
                    cpsScm {
                      scm {
                        git{
                          remote {
                            url("https://github.com/hin22001/jenkins-pipeline.git")
                          }
                          branch("*/main")
                        }
                      }
                    }
                  }
                }
        github-config: |
          unclassified:
            gitHubPluginConfig:
              configs:
                - 
ingress:
  enabled: true
  className: ""
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /jenkins
          pathType: Prefix
  tls: []
service:
  port: 8080
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local