prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
      path: /prometheus/?(.*)
      hosts:
        - ryant.internal
    prefixUrl: /prometheus
  nodeExporter:
    hostRootfs: false