ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ryant.internal
      paths:
        - path: /grafana(/|$)(.*)
          pathType: Prefix
  tls: []

service:
  port: 3000